### ISSUE TITLE
Install script has a 404 at the kernel headers

### ISSUE THREAD

**Issue by jphellemons** [recalbox/mk_arcade_joystick_rpi#68]
https://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/ latest value is 

`linux-headers-4.9.68`

install script is looking for `linux-headers-4.14.87-v7+_4.14.87-v7+-2_armhf.deb`

When I run this line manually:
https://github.com/recalbox/mk_arcade_joystick_rpi/blob/39b0094335a1bb9667b7c04cb6a6d3e9a951dda2/utils/install.sh#L18

I get:

>raspberrypi-kernel-headers is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

But when I run `sudo dpkg -i mk-arcade-joystick-rpi-0.1.4.deb`
I get:
>dpkg: warning: version '*-*' has bad syntax: version number does not start with digit
It is likely that 4.14.87-v7+ belongs to a chroot's host
Building for architecture armv7l
Module build for the currently running kernel was skipped since the
kernel source for this kernel does not seem to be installed.

I also tried this:

>pi@retropie:~/mkjoystick $ sudo apt-get install linux-headers-generic
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package linux-headers-generic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
> E: Package 'linux-headers-generic' has no installation candidate

I also tried step **3.b.1 - Download the files** But the Github url is invalid.

    git clone https://github.com/pinuct/mk_arcade_joystick_rpi/tree/customgpio

**Comment by jphellemons** [comment]
@Pinuct is the customgpio from the install readme the same as https://github.com/Pinuct/mk_arcade_joystick_rpi/tree/customgpiohotkey

**Comment by johnnyBira** [comment]
Any progress on this one? I'm also stuck
’’’sh
Module build for kernel 4.19.23+ was skipped since the
kernel headers for this kernel does not seem to be installed.
’’’

**Comment by jphellemons** [comment]
Yes. Resolved. Had to roll back the kernel

**Comment by johnnyBira** [comment]
@jphellemons which kernal did you find compatible?
